version: '3.8'
services:
  importapp:
    container_name: data-import-container
    image: data-import-image
    build: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/vacation_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: nesa1995
    depends_on:
      - pg
  searchapp:
    container_name: data-search-container
    image: data-search-image
    build: ./
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/vacation_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: nesa1995
    depends_on:
      - pg
  pg:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=nesa1995
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vacation_tracker