spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vacation_tracker?stringtype=unspecified
    username: postgres
    password: nesa1995
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

api:
  key: ABCD